import React, { useState } from "react";
import { groonabackend } from "@/api/groonabackend";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, UserPlus, CheckCircle, Settings } from "lucide-react";
import { toast } from "sonner";

export default function IndividualAllocationButton({ tenantId }) {
  const [open, setOpen] = useState(false);
  const [formData, setFormData] = useState({
    user_id: "",
    leave_type_id: "",
    allocated_days: ""
  });
  
  const queryClient = useQueryClient();

  // 1. Fetch ALL Users
  const { data: users = [] } = useQuery({
    queryKey: ['users-list', tenantId],
    queryFn: () => groonabackend.entities.User.filter({ tenant_id: tenantId }),
    enabled: open && !!tenantId
  });

  // 2. Fetch ALL Predefined Leave Types
  // This query will now pick up the types generated by "Load Defaults"
  const { data: allLeaveTypes = [] } = useQuery({
    queryKey: ['all-leave-types', tenantId],
    queryFn: () => groonabackend.entities.LeaveType.filter({ tenant_id: tenantId }),
    enabled: open && !!tenantId
  });

  const allocationMutation = useMutation({
    mutationFn: async (data) => {
      // Calls our new backend handler
      return await groonabackend.functions.invoke('allocateIndividualLeave', {
        tenant_id: tenantId,
        user_id: data.user_id,
        leave_type_id: data.leave_type_id,
        days: parseFloat(data.allocated_days),
        year: new Date().getFullYear()
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leave-balances'] });
      toast.success("Leave allocated successfully");
      setOpen(false);
      setFormData({ user_id: "", leave_type_id: "", allocated_days: "" });
    },
    onError: (error) => {
      toast.error("Allocation failed: " + error.message);
    }
  });

  const handleSubmit = () => {
    if (!formData.user_id || !formData.leave_type_id || !formData.allocated_days) {
      toast.error("Please fill in all fields");
      return;
    }
    allocationMutation.mutate(formData);
  };

  // Auto-fill default days if a type is selected
  const handleTypeChange = (typeId) => {
      const type = allLeaveTypes.find(t => t.id === typeId);
      setFormData({ 
          ...formData, 
          leave_type_id: typeId,
          allocated_days: type ? type.annual_allocation : "" 
      });
  };

  return (
    <>
      <Button
        variant="outline"
        onClick={() => setOpen(true)}
        className="flex items-center gap-2"
      >
        <UserPlus className="h-4 w-4" />
        Individual Allocation
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Allocate Leaves to User</DialogTitle>
            <DialogDescription>
              Select a user and a leave type to set their specific allowance.
            </DialogDescription>
          </DialogHeader>

          <div className="grid gap-4 py-4">
            <div className="space-y-2">
              <Label>Team Member</Label>
              <Select
                value={formData.user_id}
                onValueChange={(val) => setFormData({ ...formData, user_id: val })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select user..." />
                </SelectTrigger>
                <SelectContent>
                  {users.map((user) => (
                    <SelectItem key={user.id} value={user.id}>
                      {user.full_name} ({user.email})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Leave Type</Label>
              <Select
                value={formData.leave_type_id}
                onValueChange={handleTypeChange}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select leave type..." />
                </SelectTrigger>
                <SelectContent>
                  {allLeaveTypes.length > 0 ? (
                      allLeaveTypes.map((type) => (
                        <SelectItem key={type.id} value={type.id}>
                          {type.name} (Default: {type.annual_allocation} days)
                        </SelectItem>
                      ))
                  ) : (
                      <div className="p-2 text-center text-sm text-slate-500">
                          No leave types configured.
                      </div>
                  )}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Allocated Days</Label>
              <Input
                type="number"
                step="0.5"
                placeholder="e.g. 12"
                value={formData.allocated_days}
                onChange={(e) => setFormData({ ...formData, allocated_days: e.target.value })}
              />
              <p className="text-xs text-slate-500">
                  You can override the default annual allocation here.
              </p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
            <Button 
              onClick={handleSubmit}
              disabled={allocationMutation.isPending}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {allocationMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Allocating...
                </>
              ) : (
                'Confirm Allocation'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

